import { ConsulateRow, QueueFileItem, SlaRow, AnomaliaItem } from './types';

export const INITIAL_CONSULATES: ConsulateRow[] = [
  {
    id: 'italia-roma',
    code: '495',
    pais: 'ITALIA',
    zona: '10',
    puesto: '02 - Roma',
    numMesas: 8,
    horaCierreColombia: '9:00 AM',
    horaActualPais: '7:00 PM',
    tiempoDesdeCierre: '> 3 Hrs',
    delegadosProgress: '8/16',
    delegadosPercent: 50,
    transmisionProgress: '4/16',
    transmisionPercent: 25,
    estadoGlobal: 'CRÍTICO',
    mesas: [
      {
        id: 'mesa-roma-001',
        mesaNumber: 'Mesa 001',
        delegados: { p1: true, p2: true },
        transmision: { p1: true, p2: 'rescaneo' },
        estado: 'INCOMPLETO',
        ultimaCarga: 'Hace 12 min',
        anomalia: 'Falta de firmas en página 2 / Ilegible',
        horaCierreLocal: '14:20 LOCAL',
      },
      {
        id: 'mesa-roma-002',
        mesaNumber: 'Mesa 002',
        delegados: { p1: true, p2: true },
        transmision: { p1: 'pending', p2: 'pending' },
        estado: 'PENDIENTE',
        ultimaCarga: 'Hace 45 min',
        horaCierreLocal: '14:00 LOCAL',
      },
      {
        id: 'mesa-roma-003',
        mesaNumber: 'Mesa 003',
        delegados: { p1: 'pending' as any, p2: 'pending' as any },
        transmision: { p1: 'pending', p2: 'pending' },
        estado: 'NO INICIADO',
        ultimaCarga: '-',
        horaCierreLocal: '14:00 LOCAL',
      },
    ],
  },
  {
    id: 'paises-bajos-lahaya',
    code: '435',
    pais: 'PAISES BAJOS',
    zona: '05',
    puesto: '04 - La Haya',
    numMesas: 1,
    horaCierreColombia: '9:00 AM',
    horaActualPais: '7:00 PM',
    tiempoDesdeCierre: '< 1 Hr',
    delegadosProgress: '2/2',
    delegadosPercent: 100,
    transmisionProgress: '2/2',
    transmisionPercent: 100,
    estadoGlobal: 'COMPLETO',
    mesas: [
      {
        id: 'mesa-lahaya-001',
        mesaNumber: 'Mesa 001',
        delegados: { p1: true, p2: true },
        transmision: { p1: true, p2: true },
        estado: 'COMPLETO',
        ultimaCarga: 'Hace 50 min',
      },
    ],
  },
  {
    id: 'espana-tarragona',
    code: '355',
    pais: 'ESPAÑA',
    zona: '03',
    puesto: '06 - Tarragona',
    numMesas: 1,
    horaCierreColombia: '9:00 AM',
    horaActualPais: '7:00 PM',
    tiempoDesdeCierre: '> 2 Hrs',
    delegadosProgress: '0/2',
    delegadosPercent: 0,
    transmisionProgress: '0/2',
    transmisionPercent: 0,
    estadoGlobal: 'CRÍTICO',
    mesas: [
      {
        id: 'mesa-tarragona-001',
        mesaNumber: 'Mesa 001',
        delegados: { p1: false, p2: false },
        transmision: { p1: false, p2: false },
        estado: 'CRÍTICO',
        ultimaCarga: 'Sin reporte',
      },
    ],
  },
  {
    id: 'inglaterra-londres',
    code: '465',
    pais: 'INGLATERRA',
    zona: '05',
    puesto: '03 - Londres',
    numMesas: 1,
    horaCierreColombia: '10:00 AM',
    horaActualPais: '6:00 PM',
    tiempoDesdeCierre: '1-2 Hrs',
    delegadosProgress: '2/2',
    delegadosPercent: 100,
    transmisionProgress: '2/2',
    transmisionPercent: 50,
    estadoGlobal: 'PENDIENTE',
    mesas: [
      {
        id: 'mesa-londres-001',
        mesaNumber: 'Mesa 001',
        delegados: { p1: true, p2: true },
        transmision: { p1: true, p2: 'pending' },
        estado: 'PENDIENTE',
        ultimaCarga: 'Hace 38 min',
      },
    ],
  },
  {
    id: 'usa-nueva-york',
    code: '360',
    pais: 'ESTADOS UNIDOS',
    zona: '55',
    puesto: '02 - Nueva York',
    numMesas: 1,
    horaCierreColombia: '3:00 PM',
    horaActualPais: '1:00 PM',
    tiempoDesdeCierre: '-',
    delegadosProgress: '0/2',
    delegadosPercent: 0,
    transmisionProgress: '0/2',
    transmisionPercent: 0,
    estadoGlobal: 'NO INICIADO',
    mesas: [
      {
        id: 'mesa-ny-001',
        mesaNumber: 'Mesa 001',
        delegados: { p1: false, p2: false },
        transmision: { p1: false, p2: false },
        estado: 'NO INICIADO',
        ultimaCarga: '-',
      },
    ],
  },
];

export const INITIAL_QUEUE_FILES: QueueFileItem[] = [
  {
    id: 'file-01',
    filename: 'E14_EGIPTO_CAIRO_M1_P1_alta.jpg',
    size: '4.2 MB',
    ext: 'JPG',
    barcode: '710003992010102',
    location: 'EGIPTO > EL CAIRO > Z. 99 > P. 01 > MESA 001',
    ocrStatus: 'DUPLICADO',
    details: 'Esta página ya fue procesada y aprobada previamente',
  },
  {
    id: 'file-02',
    filename: 'E14_ROMA_ITA_M01_scan.pdf',
    size: '1.8 MB',
    ext: 'PDF',
    barcode: '390001228300101',
    location: 'ITALIA > ROMA > Z. 01 > P. 01 > MESA 001',
    ocrStatus: 'RESUELVE_ALERTA',
    details: 'Resuelve la alerta previa en Roma > Mesa 001',
  },
  {
    id: 'file-03',
    filename: 'E14_MIAMI_USA_M05_P1.jpg',
    size: '3.1 MB',
    ext: 'JPG',
    barcode: '710005992010105',
    location: 'USA > MIAMI > Z. 99 > P. 01 > MESA 005',
    ocrStatus: 'NUEVO_REGISTRO',
    ocrConfidence: 94,
    details: 'Se agregará directamente al Monitor Global',
  },
];

export const INITIAL_SLA_DATA: SlaRow[] = [
  {
    id: 'cairo',
    consulateName: 'EL CAIRO - CONSULADO',
    pais: 'EGIPTO',
    region: 'asia',
    zona: '01',
    puesto: '01',
    mesasInactivas: ['Mesa 001', 'Mesa 002'],
    horaCierreLocal: '16:00 Local',
    tiempoTranscurridoMin: 55,
    tiempoTranscurridoLabel: '+55 min',
    fase: 'fase3',
    faseLabel: '🔴 FASE 3 · CRÍTICA',
    subFaseDesc: 'Mora >40m sin lote inicial',
    notifChannel: 'WA',
    notifDespacho: 'Despachado 16:45',
    notifEstado: 'Leído (16:48) · Acuse verificado',
    notifEstadoColor: '#25D366',
  },
  {
    id: 'londres',
    consulateName: 'LONDRES - CONSULADO',
    pais: 'REINO UNIDO',
    region: 'europa',
    zona: '05',
    puesto: '03',
    mesasInactivas: ['Mesa 008'],
    horaCierreLocal: '16:00 Local',
    tiempoTranscurridoMin: 48,
    tiempoTranscurridoLabel: '+48 min',
    fase: 'fase3',
    faseLabel: '🔴 FASE 3 · CRÍTICA',
    subFaseDesc: 'Sin reporte de escaneo',
    notifChannel: 'WA',
    notifChannelExtra: 'SMS',
    notifDespacho: '16:40',
    notifEstado: 'Sin acuse recibido ⚠️ (Reintento pendiente)',
    notifEstadoColor: '#fdd400',
    notifHasWarning: true,
  },
  {
    id: 'frankfurt',
    consulateName: 'FRANKFURT - CONSULADO',
    pais: 'ALEMANIA',
    region: 'europa',
    zona: '05',
    puesto: 'MESA 012',
    mesasInactivas: ['Mesa 012'],
    horaCierreLocal: '16:00 Local',
    tiempoTranscurridoMin: 32,
    tiempoTranscurridoLabel: '+32 min',
    fase: 'fase2',
    faseLabel: '🟡 FASE 2 · ADVERTENCIA',
    subFaseDesc: 'Supera tolerancia fase 1',
    notifChannel: 'WA',
    notifDespacho: 'Despachado 16:22',
    notifEstado: 'Entregado (16:23) · Móvil activo',
    notifEstadoColor: '#3fe56c',
  },
  {
    id: 'milan',
    consulateName: 'MILÁN - CONSULADO',
    pais: 'ITALIA',
    region: 'europa',
    zona: '10',
    puesto: 'MESA 021',
    mesasInactivas: ['Mesa 021'],
    horaCierreLocal: '16:00 Local',
    tiempoTranscurridoMin: 26,
    tiempoTranscurridoLabel: '+26 min',
    fase: 'fase2',
    faseLabel: '🟡 FASE 2 · ADVERTENCIA',
    subFaseDesc: 'Aviso preventivo despachado',
    notifChannel: 'WA',
    notifDespacho: 'Despachado 16:25',
    notifEstado: 'Leído (16:27) · Operador en proceso',
    notifEstadoColor: '#25D366',
  },
  {
    id: 'paris',
    consulateName: 'PARÍS - CONSULADO',
    pais: 'FRANCIA',
    region: 'europa',
    zona: '02',
    puesto: 'MESA 003',
    mesasInactivas: ['Mesa 003'],
    horaCierreLocal: '16:00 Local',
    tiempoTranscurridoMin: 22,
    tiempoTranscurridoLabel: '+22 min',
    fase: 'fase2',
    faseLabel: '🟡 FASE 2 · ADVERTENCIA',
    subFaseDesc: 'Recién ingresada a umbral SLA',
    notifChannel: 'EMAIL',
    notifChannelExtra: 'WA',
    notifDespacho: '16:21',
    notifEstado: 'Leído (16:24) · Confirmado por c.dupont',
    notifEstadoColor: '#25D366',
  },
];

export const INITIAL_ANOMALIAS: AnomaliaItem[] = [
  {
    id: 'anom-1',
    horaAlertaLocal: '14:20 LOCAL',
    horaAlertaCol: '12:20 COL',
    pais: 'ITALIA',
    ciudad: 'ROMA',
    mesa: 'MESA 001',
    formulario: 'TRANSMISIÓN - PÁGINA 2',
    tipoAnomalia: 'SIN_FIRMAS',
    tipoLabel: 'SIN FIRMAS DETECTADAS',
    slaMinutesRemaining: 15,
    slaDisplay: '15m',
    mesaIdRef: 'mesa-roma-001',
  },
  {
    id: 'anom-2',
    horaAlertaLocal: '13:50 LOCAL',
    horaAlertaCol: '11:50 COL',
    pais: 'ESPAÑA',
    ciudad: 'MADRID',
    mesa: 'MESA 045',
    formulario: 'TRANSMISIÓN - PÁGINA 1',
    tipoAnomalia: 'ILEGIBLE_RESCANEO',
    tipoLabel: 'SOLICITUD RESCANEO',
    slaMinutesRemaining: 45,
    slaDisplay: '45m',
    mesaIdRef: 'mesa-madrid-045',
  },
  {
    id: 'anom-3',
    horaAlertaLocal: '12:20 LOCAL',
    horaAlertaCol: '10:20 COL',
    pais: 'EGIPTO',
    ciudad: 'EL CAIRO',
    mesa: 'MESA 010',
    formulario: 'TRANSMISIÓN - PÁGINA 3',
    tipoAnomalia: 'CODIGO_NO_DETECTADO',
    tipoLabel: 'CÓDIGO NO DETECTADO',
    slaMinutesRemaining: 120,
    slaDisplay: '2h',
    mesaIdRef: 'mesa-cairo-010',
  },
  {
    id: 'anom-4',
    horaAlertaLocal: '14:35 LOCAL',
    horaAlertaCol: '12:35 COL',
    pais: 'ITALIA',
    ciudad: 'MILÁN',
    mesa: 'MESA 021',
    formulario: 'TRANSMISIÓN - PÁGINA 2',
    tipoAnomalia: 'SIN_FIRMAS',
    tipoLabel: 'SIN FIRMAS DETECTADAS',
    slaMinutesRemaining: 22,
    slaDisplay: '22m',
    mesaIdRef: 'mesa-milan-021',
  },
  {
    id: 'anom-5',
    horaAlertaLocal: '11:10 LOCAL',
    horaAlertaCol: '09:10 COL',
    pais: 'REINO UNIDO',
    ciudad: 'LONDRES',
    mesa: 'MESA 008',
    formulario: 'TRANSMISIÓN - PÁGINA 1',
    tipoAnomalia: 'ILEGIBLE_RESCANEO',
    tipoLabel: 'SOLICITUD RESCANEO',
    slaMinutesRemaining: 8,
    slaDisplay: '8m',
    mesaIdRef: 'mesa-londres-008',
  },
  {
    id: 'anom-6',
    horaAlertaLocal: '15:05 LOCAL',
    horaAlertaCol: '13:05 COL',
    pais: 'FRANCIA',
    ciudad: 'PARÍS',
    mesa: 'MESA 003',
    formulario: 'TRANSMISIÓN - PÁGINA 2',
    tipoAnomalia: 'ILEGIBLE_RESCANEO',
    tipoLabel: 'SOLICITUD RESCANEO',
    slaMinutesRemaining: 30,
    slaDisplay: '30m',
    mesaIdRef: 'mesa-paris-003',
  },
  {
    id: 'anom-7',
    horaAlertaLocal: '14:50 LOCAL',
    horaAlertaCol: '12:50 COL',
    pais: 'ESPAÑA',
    ciudad: 'BARCELONA',
    mesa: 'MESA 014',
    formulario: 'TRANSMISIÓN - PÁGINA 2',
    tipoAnomalia: 'SIN_FIRMAS',
    tipoLabel: 'SIN FIRMAS DETECTADAS',
    slaMinutesRemaining: 18,
    slaDisplay: '18m',
    mesaIdRef: 'mesa-barcelona-014',
  },
  {
    id: 'anom-8',
    horaAlertaLocal: '15:15 LOCAL',
    horaAlertaCol: '13:15 COL',
    pais: 'ALEMANIA',
    ciudad: 'BERLÍN',
    mesa: 'MESA 002',
    formulario: 'TRANSMISIÓN - PÁGINA 1',
    tipoAnomalia: 'ILEGIBLE_RESCANEO',
    tipoLabel: 'SOLICITUD RESCANEO',
    slaMinutesRemaining: 50,
    slaDisplay: '50m',
    mesaIdRef: 'mesa-berlin-002',
  },
];
